version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_HOST: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
    networks:
      - backend

  server:
    image: ${DOCKER_USER}/${PROD_NAME}-server:latest
    container_name: server
    restart: unless-stopped
    env_file:
      - .env
      - ./apps/server/.env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@postgres:5432/${DATABASE_NAME}?schema=public
    networks:
      - backend
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres

  website:
    image: ${DOCKER_USER}/${PROD_NAME}-website:latest
    container_name: website
    restart: unless-stopped
    env_file:
      - .env
      - ./apps/website/.env.local
    environment:
      - NODE_ENV=production
      - APP_HTTP_URL=http://server:3000/trpc
      - DATABASE_URL=postgresql://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@postgres:5432/${DATABASE_NAME}?schema=public
    networks:
      - backend
    depends_on:
      - server

  admin:
    image: ${DOCKER_USER}/${PROD_NAME}-admin:latest
    container_name: admin
    restart: unless-stopped
    env_file:
      - .env
      - ./apps/admin/.env.local
    environment:
      - NODE_ENV=production
      - APP_HTTP_URL=http://server:3000/trpc
      - DATABASE_URL=postgresql://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@postgres:5432/${DATABASE_NAME}?schema=public
    networks:
      - backend
    depends_on:
      - server

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
