packages:
  - apps/*
  - packages/*

nodeLinker: hoisted

onlyBuiltDependencies:
  - '@heroui/shared-utils'
  - '@nestjs/core'
  - '@prisma/engines'
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
