import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '../styles/index.css';

import { getDefaultThemeFromCookie } from '@package/ui/theme-server';
import type { ReactNode } from 'react';

import ToastNotification from '@/components/Toast';
import { auth } from '@/utils/next-auth';

import AuthFeedbackWatcher from '@/components/auth/AuthFeedbackWatcher';
import SessionWatcher from '@/components/auth/SessionWatcher';
import { Providers } from './providers';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    // icon: '/favicon.ico',
    // apple: '/logo192.png',
  },
  // manifest: '/manifest.json',
};

export const viewport = {
  themeColor: '#000000',
  width: 'device-width',
  initialScale: 1,
};

export default async function RootLayout({ children }: { children: ReactNode }) {
  const session = await auth();
  const defaultTheme = await getDefaultThemeFromCookie();

  return (
    <html
      lang="en"
      className={`custom-scrollbar scroll-smooth ${defaultTheme}`}
      suppressHydrationWarning
    >
      <body
        id="root"
        className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased flex min-h-screen flex-col bg-lightPrimary dark:bg-navy-900`}
        suppressHydrationWarning
      >
        <Providers session={session} defaultThemeFromCookie={defaultTheme}>
          <ToastNotification />
          <SessionWatcher />
          <AuthFeedbackWatcher />
          {/* Main content */}
          <div className="text-gray-900 dark:text-white">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
