import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '../styles/index.css';

import { getDefaultThemeFromCookie } from '@package/ui/theme-server';
import type { ReactNode } from 'react';

import { auth } from '@/utils/next-auth';

import { Providers } from './providers';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: { children: ReactNode }) {
  const session = await auth();
  const defaultTheme = await getDefaultThemeFromCookie();

  return (
    <html lang="en" className="scroll-smooth" suppressHydrationWarning>
      <body
        id="root"
        className={`flex min-h-screen flex-col ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers session={session} defaultThemeFromCookie={defaultTheme}>
          {/* Main content */}
          <div className="text-gray-900 dark:text-white">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
